export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const SET_SELECTED_IMAGE = 'SET_SELECTED_IMAGE'

export const NEXT_PAGE = 'NEXT_PAGE'

export const INC_TOTAL_DOWNLOADED_IMAGES = 'INC_TOTAL_DOWNLOADED_IMAGES'

export const API_KEY = 'a539d43260a16964f47a80459496f492'
export const IMAGES_REP_PAGE = 50
